name: Manual .Net Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
jobs:
  Print-Info:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”” Start workflow
        run: echo "Workflow started..."

      - name: ðŸ“ƒ Show runtime context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"
          echo "OS: ${{ runner.os }}
  
      
