name: Manual .Net Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
jobs:
  Print-Info:
    runs-on: ubuntu-latest

    steps:

      - name: Show runtime context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"
          echo "OS: ${{ runner.os }}"

      - name: Github to Json
        run: echo "${{ toJSON(github) }}"
      - name: print Job Context
        run: echo "${{ toJSON(job) }}"

  build-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        version: [9.0, 8.0]          

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: setup .Net
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build Code
        run: dotnet build

      - name: Print matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using .Net version: ${{matrix.version}}

      
  
      
